//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.23 at 06:15:48 PM CST 
//


package bccr.fva.cr.stub;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlgoritmoDeHash.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AlgoritmoDeHash"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Sha256"/&gt;
 *     &lt;enumeration value="Sha384"/&gt;
 *     &lt;enumeration value="Sha512"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AlgoritmoDeHash")
@XmlEnum
public enum AlgoritmoDeHash {

    @XmlEnumValue("Sha256")
    SHA_256("Sha256"),
    @XmlEnumValue("Sha384")
    SHA_384("Sha384"),
    @XmlEnumValue("Sha512")
    SHA_512("Sha512");
    private final String value;

    AlgoritmoDeHash(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AlgoritmoDeHash fromValue(String v) {
        for (AlgoritmoDeHash c: AlgoritmoDeHash.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
