//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.23 at 06:15:48 PM CST 
//


package bccr.fva.cr.stub;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bccr.fva.cr.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bccr.fva.cr.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedCoFirma }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedCoFirma createRecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedCoFirma() {
        return new RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedCoFirma();
    }

    /**
     * Create an instance of {@link SolicitudDeFirma }
     * 
     */
    public SolicitudDeFirma createSolicitudDeFirma() {
        return new SolicitudDeFirma();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedCoFirmaResponse }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedCoFirmaResponse createRecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedCoFirmaResponse() {
        return new RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedCoFirmaResponse();
    }

    /**
     * Create an instance of {@link RespuestaDeLaSolicitud }
     * 
     */
    public RespuestaDeLaSolicitud createRespuestaDeLaSolicitud() {
        return new RespuestaDeLaSolicitud();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedContraFirma }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedContraFirma createRecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedContraFirma() {
        return new RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedContraFirma();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedContraFirmaResponse }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedContraFirmaResponse createRecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedContraFirmaResponse() {
        return new RecibaLaSolicitudDeSelladoElectronicoXmlEnvelopedContraFirmaResponse();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoMSOffice }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoMSOffice createRecibaLaSolicitudDeSelladoElectronicoMSOffice() {
        return new RecibaLaSolicitudDeSelladoElectronicoMSOffice();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoMSOfficeResponse }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoMSOfficeResponse createRecibaLaSolicitudDeSelladoElectronicoMSOfficeResponse() {
        return new RecibaLaSolicitudDeSelladoElectronicoMSOfficeResponse();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoPdf }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoPdf createRecibaLaSolicitudDeSelladoElectronicoPdf() {
        return new RecibaLaSolicitudDeSelladoElectronicoPdf();
    }

    /**
     * Create an instance of {@link SolicitudDeFirmaPdf }
     * 
     */
    public SolicitudDeFirmaPdf createSolicitudDeFirmaPdf() {
        return new SolicitudDeFirmaPdf();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoPdfResponse }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoPdfResponse createRecibaLaSolicitudDeSelladoElectronicoPdfResponse() {
        return new RecibaLaSolicitudDeSelladoElectronicoPdfResponse();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoOdf }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoOdf createRecibaLaSolicitudDeSelladoElectronicoOdf() {
        return new RecibaLaSolicitudDeSelladoElectronicoOdf();
    }

    /**
     * Create an instance of {@link RecibaLaSolicitudDeSelladoElectronicoOdfResponse }
     * 
     */
    public RecibaLaSolicitudDeSelladoElectronicoOdfResponse createRecibaLaSolicitudDeSelladoElectronicoOdfResponse() {
        return new RecibaLaSolicitudDeSelladoElectronicoOdfResponse();
    }

    /**
     * Create an instance of {@link ElServicioEstaDisponible }
     * 
     */
    public ElServicioEstaDisponible createElServicioEstaDisponible() {
        return new ElServicioEstaDisponible();
    }

    /**
     * Create an instance of {@link ElServicioEstaDisponibleResponse }
     * 
     */
    public ElServicioEstaDisponibleResponse createElServicioEstaDisponibleResponse() {
        return new ElServicioEstaDisponibleResponse();
    }

}
