//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.23 at 06:15:48 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bccr.fva.cr/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bccr.fva.cr.stub;
