//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.23 at 06:15:48 PM CST 
//


package bccr.fva.cr.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespuestaDeLaSolicitud complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespuestaDeLaSolicitud"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentoFirmado" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="FueExitosa" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="CodigoDeError" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="HashDocumentoFirmado" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="IDAlgoritmoHashDocumentoFirmado" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespuestaDeLaSolicitud", propOrder = {
    "documentoFirmado",
    "fueExitosa",
    "codigoDeError",
    "hashDocumentoFirmado",
    "idAlgoritmoHashDocumentoFirmado"
})
public class RespuestaDeLaSolicitud {

    @XmlElement(name = "DocumentoFirmado")
    protected byte[] documentoFirmado;
    @XmlElement(name = "FueExitosa")
    protected boolean fueExitosa;
    @XmlElement(name = "CodigoDeError")
    protected int codigoDeError;
    @XmlElement(name = "HashDocumentoFirmado")
    protected byte[] hashDocumentoFirmado;
    @XmlElement(name = "IDAlgoritmoHashDocumentoFirmado")
    protected int idAlgoritmoHashDocumentoFirmado;

    /**
     * Gets the value of the documentoFirmado property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getDocumentoFirmado() {
        return documentoFirmado;
    }

    /**
     * Sets the value of the documentoFirmado property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setDocumentoFirmado(byte[] value) {
        this.documentoFirmado = value;
    }

    /**
     * Gets the value of the fueExitosa property.
     * 
     */
    public boolean isFueExitosa() {
        return fueExitosa;
    }

    /**
     * Sets the value of the fueExitosa property.
     * 
     */
    public void setFueExitosa(boolean value) {
        this.fueExitosa = value;
    }

    /**
     * Gets the value of the codigoDeError property.
     * 
     */
    public int getCodigoDeError() {
        return codigoDeError;
    }

    /**
     * Sets the value of the codigoDeError property.
     * 
     */
    public void setCodigoDeError(int value) {
        this.codigoDeError = value;
    }

    /**
     * Gets the value of the hashDocumentoFirmado property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getHashDocumentoFirmado() {
        return hashDocumentoFirmado;
    }

    /**
     * Sets the value of the hashDocumentoFirmado property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setHashDocumentoFirmado(byte[] value) {
        this.hashDocumentoFirmado = value;
    }

    /**
     * Gets the value of the idAlgoritmoHashDocumentoFirmado property.
     * 
     */
    public int getIDAlgoritmoHashDocumentoFirmado() {
        return idAlgoritmoHashDocumentoFirmado;
    }

    /**
     * Sets the value of the idAlgoritmoHashDocumentoFirmado property.
     * 
     */
    public void setIDAlgoritmoHashDocumentoFirmado(int value) {
        this.idAlgoritmoHashDocumentoFirmado = value;
    }

}
